# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2baa9aca6e1f3026807c4aec6fd09e4e542d37f947475b711edd03fb2a6a7ef4eb78ff92c9e764cd0496de65d13d0a9daa2ea6db151a44ac1ef375736ce1de

test:
  secret_key_base: 35512d65f91fe94b12a1c8442cb9d66ac4730048cbb625b5a4d36629ad60ee735f0166f8a086f834e278b84a632da3194e3dbd8790f0d29f6ab1650d7606214b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
